import { Platform, StatusBar, StyleSheet, Dimensions } from "react-native";

export const AppColors = {
  PRIMARY: "#fbb42e",
  SECONDARY: "#f86730",
  BARS: "#1b1b22",
  WHITE: "#ffffff",
  TEXT_BOX_TRANS: "rgba(27, 27, 34, 0.5)",
  TRANSPARENCY: "rgba(119, 114, 114, 0.3)",
  STAR: "#fbb42e",
  COOL_GREEN: "#34c759",
  BLACK: "#000000",
  BLUE: "#3b5997",
  BG: "#212428",
  TEXT_BOX_TRANSPARENT: "rgba(27, 27, 34, 0.5)",
  // TRANSPARENT: "rgba(119, 114, 114, 0.3)",
  LOGO_COLOR: "#ffbd59",
  BARRAS: "#1b1b22",
  GREY: "#434343",
  INPUT_BG: "#22222c",
  LIGHT_GRAY: "#F5F5F5",
  SEARCH_GRAY: "#484848",
  DIVIDER_GRAY: "#434343",
  BAR: "#292929",
  VENUE_CARD: "#22222c",
  TRANSPARENT: "rgba(0, 0, 0, 0)",

  CHAT_LEFT: "#434343",
  CHAT_RIGHT: "#22222c",
  RED: "#FF6962",
  LIGHTGRAY: "#2D2D35",
  LIGHT_BLACK: "#292930",
  LIGHR_WHITE: "#B1B1AF",
  DARK_GRAY: "#212428",
  GREEN_COLOR: "#128400",
};

const { width, height } = Dimensions.get("window");

const [shortDimension, longDimension] =
  width < height ? [width, height] : [height, width];
const guidelineBaseWidth = 350;
const guidelineBaseHeight = 680;

export const scale = (size: number) =>
  (shortDimension / guidelineBaseWidth) * size;
export const verticalScale = (size: number) =>
  (longDimension / guidelineBaseHeight) * size;
export const moderateScale = (size: number, factor = 0.5) =>
  size + (scale(size) - size) * factor;

export const AppStyles = StyleSheet.create({
  empty_text_home: {
    color: AppColors.LIGHT_GRAY,
    marginHorizontal: 15,
    fontSize: 15,
    alignSelf: "center",
  },
  empty_text: {
    color: AppColors.LIGHT_GRAY,
    marginHorizontal: 10,
  },
  mh15: {
    marginHorizontal: 15,
  },
  mv15: {
    marginVertical: 15,
  },
  mt15: {
    marginTop: 15,
  },
  mt25: {
    marginTop: 25,
  },
  mb25: {
    marginBottom: 25,
  },
  error_text: {
    color: AppColors.RED,
    marginHorizontal: 15,
    marginVertical: 5,
  },
  staff_table: {
    color: AppColors.LOGO_COLOR,
    fontFamily: "Roboto-Bold",
    textAlign: "left",
    paddingTop: 2,
  },
  base_icon: {
    backgroundColor: AppColors.TRANSPARENT,
  },
  staff_booking_title: {
    color: AppColors.WHITE,
    fontSize: 16,
    fontFamily: "Roboto-Bold",
    textAlign: "left",
  },
  staff_booking_date: {
    color: AppColors.SEARCH_GRAY,
    fontSize: 13,
    textAlign: "left",
    paddingTop: 1,
  },
  booking_customer_pic: {
    marginRight: 15,
  },
  verification_title: {
    fontFamily: "Roboto-Bold",
    fontSize: 21,
    color: AppColors.WHITE,
    marginTop: 20,
    marginBottom: 10,
    paddingVertical: 5,
  },
  verification_paragraph: {
    textAlign: "left",
    fontFamily: "Roboto",
    fontSize: 14,
  },
  verification_img: {
    width: "100%",
    height: 200,
    resizeMode: "contain",
    marginTop: 35,
  },
  venue_open_hours: {
    color: AppColors.LOGO_COLOR,
    fontSize: 13,
    textAlign: "left",
    marginBottom: 15,
    fontFamily: "Roboto-Bold",
  },
  text_18_color_bold: {
    color: AppColors.LOGO_COLOR,
    fontFamily: "Roboto-Bold",
    fontSize: 18,
  },
  text_16_color: {
    color: AppColors.LOGO_COLOR,
    fontFamily: "Roboto",
    fontSize: 16,
  },
  dialog_title: {
    fontSize: 16,
    color: AppColors.WHITE,
    fontFamily: "Roboto-Bold",
  },
  staff_page_title: {
    fontFamily: "Roboto-Bold",
    fontSize: 20,
    color: AppColors.WHITE,
    paddingTop: 15,
    paddingHorizontal: 15,
  },
  text_13: {
    fontSize: 13,
    fontFamily: "Roboto",
  },
  text_14: {
    fontSize: 14,
    fontFamily: "Roboto",
  },
  text_16: {
    fontSize: 16,
    fontFamily: "Roboto",
  },
  text_18: {
    fontSize: 18,
    fontFamily: "Roboto",
  },
  booking_policy_text: {
    color: AppColors.LIGHT_GRAY,
    fontSize: 13,
  },
  booking_data_divider: {
    marginVertical: 15,
    backgroundColor: AppColors.DIVIDER_GRAY,
  },
  booking_item_title: {
    color: AppColors.LOGO_COLOR,
    fontSize: 17,
    fontFamily: "Roboto-Bold",
  },
  booking_item_value: {
    color: AppColors.WHITE,
    fontSize: 15,
  },
  booking_container: {
    marginHorizontal: 15,
    marginBottom: 25,
  },
  booking_chat_btn: {
    backgroundColor: AppColors.LOGO_COLOR,
    borderRadius: 80,
  },
  booking_chat_btn_title: {
    fontSize: 16,
    fontFamily: "Roboto-Bold",
    textAlign: "center",
  },
  booking_amount: {
    color: AppColors.LOGO_COLOR,
    fontSize: 14,
    textAlign: "left",
    paddingTop: 2,
    fontFamily: "Roboto-Bold",
  },
  booking_code: {
    color: AppColors.WHITE,
    fontSize: 13,
    textAlign: "left",
    paddingTop: 2,
  },
  booking_date: {
    color: AppColors.WHITE,
    fontSize: 13,
    textAlign: "left",
    paddingTop: 2,
    fontFamily: "Roboto-Bold",
  },
  chat_container: {
    flex: 1,
    backgroundColor: AppColors.BG,
    position: "relative",
  },
  bookings_title: {
    fontFamily: "Roboto-Bold",
    fontSize: 22,
    color: AppColors.WHITE,
    paddingTop: 15,
    paddingHorizontal: 10,
  },
  tab_view: {
    backgroundColor: AppColors.BG,
  },
  tab_view_indicator: {
    backgroundColor: AppColors.LOGO_COLOR,
  },
  tab_view_label: {
    textTransform: "capitalize",
    fontSize: 14,
  },
  table_detail_policy: {
    color: AppColors.LIGHT_GRAY,
    fontSize: 13,
  },
  button_outlined_label: {
    fontSize: 13,
    textTransform: "capitalize",
  },
  button_outlined_small: {},
  table_detail_bottom: {
    marginBottom: 25,
    width: "100%",
  },
  table_detail_row_total: {
    fontFamily: "Roboto-Bold",
    color: AppColors.LIGHT_GRAY,
    fontSize: 16,
  },
  table_detail_row_medium: {
    color: AppColors.LIGHT_GRAY,
    fontSize: 16,
  },
  table_detail_row: {
    color: AppColors.LIGHT_GRAY,
    fontSize: 15,
  },
  table_detail_header: {
    fontFamily: "Roboto-Bold",
    fontSize: 16,
    color: AppColors.LOGO_COLOR,
  },
  table_detail_main: {
    fontFamily: "Roboto-Bold",
    fontSize: 18,
    color: AppColors.LOGO_COLOR,
    marginVertical: 5,
    marginHorizontal: 10,
  },
  table_detail_title: {
    fontFamily: "Roboto-Bold",
    fontSize: 18,
    color: AppColors.LOGO_COLOR,
    marginVertical: 5,
    marginHorizontal: 10,
  },
  table_detail_text: {
    color: AppColors.LIGHT_GRAY,
    marginHorizontal: 10,
  },
  user_avatar: {
    backgroundColor: AppColors.TRANSPARENT,
  },

  table_list_type: {
    fontFamily: "Roboto-Bold",
    fontSize: 18,
    color: AppColors.LOGO_COLOR,
    marginHorizontal: 10,
  },
  table_list_title: {
    fontSize: 16,
    color: AppColors.WHITE,
  },
  table_list_detail: {
    fontSize: 13,
    color: AppColors.DIVIDER_GRAY,
    marginVertical: 5,
  },
  detail_policy_text: {
    color: AppColors.LIGHT_GRAY,
    marginHorizontal: 10,
    fontSize: 13,
    marginBottom: 25,
  },
  detail_card_main: {
    fontFamily: "Roboto-Bold",
    fontSize: moderateScale(18),
    color: AppColors.LOGO_COLOR,
    marginVertical: verticalScale(5),
    marginHorizontal: scale(10),
  },
  detail_card_icon: {
    backgroundColor: AppColors.BARS,
    position: "absolute",
    left: -5,
    top: 0,
  },
  detail_card_container: {
    marginHorizontal: 5,
    marginVertical: 10,
    backgroundColor: AppColors.BG,
    padding: 10,
    flexDirection: "row",
    flexWrap: "wrap",
  },
  detail_card_divider: {
    marginVertical: 15,
    backgroundColor: AppColors.DIVIDER_GRAY,
  },
  detail_card_small: {
    fontSize: 14,
    textAlign: "left",
    color: AppColors.WHITE,
    paddingLeft: 20,
  },
  detail_card_row: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  detail_card_name: {
    color: AppColors.WHITE,
    fontSize: 22,
    fontFamily: "Roboto-Bold",
    textAlign: "left",
    paddingVertical: 2,
  },
  button_bottom: {
    position: "absolute",
    bottom: 0,
    marginHorizontal: 10,
    textTransform: "capitalize",
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 25,
    flex: 1,
  },
  service_rate_title: {
    fontSize: 16,
    paddingVertical: 5,
  },
  help_title: {
    fontFamily: "Roboto-Bold",
    fontSize: 16,
    color: AppColors.LOGO_COLOR,
    marginBottom: 5,
  },
  item_text_white: {
    color: AppColors.WHITE,
  },
  screen_container: {},
  view_pic: {
    marginVertical: 15,
    flex: 1,
  },
  venue_data_select: {
    fontSize: 14,
    paddingVertical: 15,
  },
  venue_data_divider: {
    marginVertical: 15,
    backgroundColor: AppColors.DIVIDER_GRAY,
  },
  venue_data_text: {
    fontSize: 16,
    textAlign: "left",
    fontFamily: "Roboto",
    color: AppColors.WHITE,
  },
  venue_data_title: {
    color: AppColors.LOGO_COLOR,
    fontSize: 20,
    fontFamily: "Roboto-Bold",
    textAlign: "left",
    marginBottom: 10,
  },
  venue_data_container: {
    flexDirection: "column",
    flex: 1,
    marginHorizontal: 15,
    marginBottom: 25,
  },
  venue_detail_link_container: {
    flex: 1,
    alignItems: "center",
    marginBottom: 25,
  },
  venue_detail_link: {
    backgroundColor: AppColors.VENUE_CARD,
  },
  venue_detail_link_text: {
    fontFamily: "Roboto-Bold",
  },
  venue_detail_divider: {
    marginVertical: 25,
    backgroundColor: AppColors.WHITE,
    marginHorizontal: 10,
  },
  venue_address: {
    fontSize: 14,
    textAlign: "left",
    color: AppColors.WHITE,
  },
  venue_detail_name: {
    color: AppColors.LOGO_COLOR,
    fontSize: 22,
    fontFamily: "Roboto-Bold",
    textAlign: "left",
    paddingTop: 5,
  },
  venue_detail_header_in: {
    paddingHorizontal: 15,
    paddingTop: 20,
    flexDirection: "column",
  },
  venue_detail_header: {
    borderRadius: 12,
    marginTop: -65,
    marginLeft: 15,
    marginRight: 15,
    marginBottom: 15,
    backgroundColor: AppColors.VENUE_CARD,
    flexDirection: "column",
  },
  venue_detail_pic: {
    resizeMode: "cover",
    height: 287,
    width: "100%",
  },
  venue_list_action: {
    backgroundColor: AppColors.BAR,
  },
  venue_list_row: {
    flexDirection: "row-reverse",
  },
  venue_list_type: {
    color: AppColors.LOGO_COLOR,
    fontSize: moderateScale(13),
    textAlign: "left",
    paddingTop: 2,
    fontFamily: "Roboto-Bold",
  },
  flat_container: {
    marginTop: 15,
    marginBottom: 15,
  },
  venue_list_rating: {
    backgroundColor: AppColors.BG,
  },
  venue_list_pic: {
    borderRadius: 12,
    resizeMode: "cover",
    width: 140,
    height: 140,
    marginRight: 15,
  },
  venue_list_container: {
    marginLeft: 5,
    marginRight: 5,
    marginBottom: 5,
    backgroundColor: AppColors.BG,
    padding: 8,
    flexDirection: "row",
    flexWrap: "wrap",
  },

  home_screen_container: {
    paddingTop: 25,
    paddingBottom: 25,
  },

  venue_rating: {
    backgroundColor: AppColors.VENUE_CARD,
  },
  venue_rating_big: {
    backgroundColor: AppColors.BG,
  },
  venue_card_type: {
    color: AppColors.LOGO_COLOR,
    fontSize: 13,
    textAlign: "left",
  },
  venue_card_rating: {
    color: AppColors.WHITE,
    fontSize: 13,
    fontFamily: "Roboto-Bold",
    textAlign: "left",
  },
  venue_rating_detail_big: {
    fontFamily: "Roboto-Bold",
    fontSize: 16,
    color: AppColors.LOGO_COLOR,
    paddingVertical: 8,
  },
  venue_rating_detail_big_white: {
    fontSize: 16,
    color: AppColors.WHITE,
    paddingVertical: 8,
  },
  venue_card_name: {
    color: AppColors.WHITE,
    fontSize: moderateScale(14),
    fontFamily: "Roboto-Bold",
    textAlign: "left",
  },
  venue_card_pic: {
    borderRadius: 12,
    resizeMode: "cover",
    width: 140,
    height: 135,
    marginBottom: 5,
  },
  venue_container: {
    marginLeft: 15,
    backgroundColor: AppColors.VENUE_CARD,
    borderRadius: 12,
    width: 156,
    padding: 8,
  },
  bottom_navigation_bar: {
    backgroundColor: AppColors.LIGHT_BLACK,
    paddingTop: 10,
  },
  fab: {
    position: "absolute",
    margin: 15,
    right: 0,
    bottom: 0,
    backgroundColor: AppColors.LOGO_COLOR,
    color: AppColors.WHITE,
  },
  fab_payment: {
    position: "absolute",
    marginHorizontal: 15,
    marginBottom: 25,
    right: 0,
    bottom: 0,
    backgroundColor: AppColors.LOGO_COLOR,
    color: AppColors.BG,
  },
  fab_top: {
    position: "absolute",
    marginTop: 44,
    marginLeft: 8,
    left: 0,
    top: 0,
    color: AppColors.WHITE,
    shadowColor: AppColors.BARS,
    backgroundColor: AppColors.BARS,
  },
  fab_top_right: {
    position: "absolute",
    marginTop: 44,
    marginRight: 8,
    right: 0,
    top: 0,
    color: AppColors.WHITE,
    shadowColor: AppColors.BARS,
    backgroundColor: AppColors.BARS,
  },
  fab_current_location: {
    position: "absolute",
    margin: 10,
    right: 0,
    bottom: "18.5%",
  },
  fab_map_filters: {
    position: "absolute",
    marginLeft: 10,
    marginBottom: 13,
    left: 0,
    bottom: "18.5%",
    textTransform: "capitalize",
  },
  drawer_title: {
    fontFamily: "Roboto-Bold",
    fontSize: 16,
    color: AppColors.WHITE,
    textAlign: "center",
    marginTop: 10,
    marginBottom: 10,
  },
  drawer_section_title: {
    fontSize: 14,
    color: AppColors.LOGO_COLOR,
    marginStart: 15,
    marginTop: 5,
    marginBottom: 5,
  },
  drawer_version: {
    fontSize: 14,
    color: AppColors.LOGO_COLOR,
    textAlign: "center",
    marginTop: 15,
    fontFamily: "Roboto-Bold",
  },
  drawer_content: {
    flex: 1,
    // paddingTop: Platform.OS === 'android' ? 25 : 22,
    paddingTop: 35,
  },
  drawer_user_content: {},
  drawer_item: {},
  item_title: {
    color: AppColors.WHITE,
    fontSize: 16,
  },
  item_title_help: {
    fontFamily: "Roboto-Bold",
    fontSize: 18,
    color: AppColors.LOGO_COLOR,
  },
  splash_container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1b1b22",
  },
  list_item: {
    paddingTop: 5,
    paddingBottom: 5,
  },
  items_divider: {
    marginHorizontal: 10,
    backgroundColor: AppColors.DIVIDER_GRAY,
  },
  divider: {
    marginHorizontal: 10,
    marginVertical: 5,
    backgroundColor: AppColors.DIVIDER_GRAY,
  },
  loading_view: {
    flexDirection: "row",
    alignItems: "center",
  },
  loading_paragraph: {
    fontFamily: "Roboto-Bold",
    fontSize: 16,
  },
  snackbar_wrapper: {
    marginBottom: 15,
    color: "red",
  },
  snackbar_content: {
    backgroundColor: AppColors.LIGHT_GRAY,
    borderRadius: 12,
    color: "red",
  },
  m_h_15: {
    marginHorizontal: 15,
  },
  m10: {
    margin: 10,
  },
  m5: {
    margin: 5,
  },
  view_text_center: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignSelf: "center",
    alignItems: "center",
  },
  content_area: {
    flex: 1,
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
    backgroundColor: AppColors.BG,
  },
  page_title: {
    fontFamily: "Roboto-Bold",
    fontSize: 18,
    color: AppColors.WHITE,
    textAlign: "center",
  },
  page_title_small: {
    fontFamily: "Roboto-Bold",
    fontSize: 16,
    color: AppColors.WHITE,
    textAlign: "center",
  },
  modal_title: {
    fontFamily: "Roboto-Bold",
    fontSize: 20,
    color: AppColors.WHITE,
    textAlign: "center",
    paddingVertical: 10,
    backgroundColor: AppColors.BARS,
    width: "100%",
  },
  modal_subtitle: {
    fontFamily: "Roboto-Bold",
    fontSize: 22,
    textAlign: "center",
    color: AppColors.WHITE,
    paddingTop: 30,
  },
  title: {
    fontFamily: "Roboto-Bold",
    fontSize: 22,
    color: AppColors.WHITE,
    paddingVertical: 5,
  },
  title_center: {
    fontFamily: "Roboto-Bold",
    fontSize: 22,
    color: AppColors.WHITE,
    textAlign: "center",
    paddingVertical: 5,
  },
  title_center_small: {
    fontSize: 16,
    color: AppColors.WHITE,
    textAlign: "center",
  },
  main: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    textAlign: "left",
    color: AppColors.WHITE,
  },
  search_title: {
    fontFamily: "Roboto-Bold",
    fontSize: 22,
    color: AppColors.LOGO_COLOR,
    marginVertical: 10,
  },
  search_text: {
    color: AppColors.WHITE,
    marginBottom: 10,
    fontSize: 18,
  },
  basic_text: {
    color: AppColors.WHITE,
    marginBottom: 10,
    fontSize: 16,
  },
  search_location: {
    backgroundColor: AppColors.LOGO_COLOR,
  },
  search_input: {
    borderRadius: 12,
    margin: 10,
  },
  search_use: {
    fontFamily: "Roboto-Bold",
    fontSize: 16,
    color: AppColors.WHITE,
    textAlign: "center",
    marginVertical: 10,
  },
  search_small_title: {
    fontFamily: "Roboto-Bold",
    fontSize: 18,
    color: AppColors.WHITE,
    marginVertical: 10,
    marginHorizontal: 15,
  },
  map_google: {
    flex: 5,
    paddingTop: 10,
    paddingBottom: 10,
  },
  map_footer_row: {
    flexDirection: "row",
    flexWrap: "wrap",
    backgroundColor: AppColors.BARS,
    marginHorizontal: 15,
  },
  map_container: {},
  text_style: {
    fontFamily: "Roboto-Regular",
    fontSize: 14,
    textAlign: "left",
    color: AppColors.WHITE,
  },
  text_login_logo: {
    color: AppColors.WHITE,
    fontSize: 18,
    fontFamily: "Roboto-Bold",
    textAlign: "center",
    paddingTop: 20,
    paddingBottom: 20,
  },
  text_login: {
    textAlign: "center",
    color: AppColors.LOGO_COLOR,
  },
  text_forgot: {
    textAlign: "center",
    color: AppColors.LOGO_COLOR,
    fontSize: 16,
  },
  text_skip: {
    textAlign: "center",
    color: AppColors.WHITE,
    fontSize: 16,
  },
  forgot_your_password: {
    width: 164,
    height: 19,
    fontFamily: "Roboto",
    fontSize: 16,
    fontWeight: "500",
    fontStyle: "normal",
    letterSpacing: 0,
    textAlign: "left",
    color: AppColors.WHITE,
  },
  home_logo_container: {
    marginBottom: 25,
    marginTop: 0,
  },
  home_logo: {
    width: "100%",
    height: 110,
    resizeMode: "contain",
  },
  logo_contenedor_sign_in: {
    flexWrap: "wrap",
    height: 120,
    // marginTop: 20,
    alignSelf: "center",
  },
  sign_in_logo: {
    flex: 1,
    height: 120,
    justifyContent: "center",
    alignContent: "center",
  },
  logo_sign_in: {
    flex: 1,
    resizeMode: "contain",
  },
  redes_icon: {
    width: 11.4,
    height: 22,
  },
  redes_text: {
    width: 149,
    height: 19,
    fontFamily: "Roboto",
    fontSize: 16,
    fontWeight: "bold",
    fontStyle: "normal",
    letterSpacing: 0,
    textAlign: "left",
    color: AppColors.WHITE,
    textTransform: "capitalize",
  },
  text_login_register: {
    fontSize: 16,
    color: AppColors.WHITE,
  },
  text_login_register_orange: {
    fontSize: 16,
    color: AppColors.LOGO_COLOR,
    paddingStart: 5,
  },
  text_underline: {
    fontSize: 16,
    paddingStart: 5,
    textDecorationLine: "underline",
  },
  container_white: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  table_row: {
    width: 343,
    height: 56,
    borderRadius: 12,
    backgroundColor: AppColors.TEXT_BOX_TRANSPARENT,
  },
  content_start_35: {
    width: "35%",
    alignItems: "flex-start",
  },
  content_start: {
    width: "50%",
    alignItems: "flex-start",
  },
  content_end: {
    width: "50%",
    alignItems: "flex-end",
  },
  content_end_left: {
    width: "50%",
    alignItems: "flex-start",
  },
  container: {
    flex: 1,
    backgroundColor: AppColors.BG,
  },
  row: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 15,
  },
  wrapper: {
    flex: 1,
  },
  row_wrap: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  column_wrap: {
    flexDirection: "column",
    flex: 1,
    alignItems: "flex-start",
  },
  row_8_16: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  row_4_2: {
    flexDirection: "row",
    alignItems: "center",

    justifyContent: "space-between",
    paddingVertical: 4,
    paddingHorizontal: 2,
  },
  button: {
    margin: 10,
    textTransform: "capitalize",
    fontSize: 16,
    fontWeight: "bold",
  },
  button_safe: {
    marginHorizontal: 10,
    marginTop: 15,
    textTransform: "capitalize",
    fontSize: 16,
    fontWeight: "bold",
  },
  button_safe_nm: {
    marginHorizontal: 10,
    textTransform: "capitalize",
    fontSize: 16,
    fontWeight: "bold",
  },
  link_button: {
    marginVertical: 5,
    width: "40%",
  },
  modal_bottom: {
    position: "absolute",
    bottom: 0,
    marginBottom: 25,
    width: "100%",
  },
  button_content: {
    paddingVertical: 5,
  },
  button_label: {
    fontFamily: "Roboto-Bold",
    fontSize: 16,
  },
  link_button_label: {
    fontFamily: "Roboto",
    fontSize: 16,
  },
  button_next: {
    marginVertical: 4,
    marginHorizontal: 8,
    //width:100,
    height: 48,
    alignContent: "center",
    alignItems: "center",
    textTransform: "capitalize",
    fontFamily: "Roboto",
    fontSize: 16,
    fontStyle: "normal",
    letterSpacing: 0,

    color: AppColors.WHITE,
  },
  button_form: {
    /*marginVertical: 4,
        marginHorizontal: 8,
        height: 50,
        borderRadius: 8,
        alignContent: "center",
        alignItems: "center",
        textTransform: "capitalize",
        fontFamily: "Roboto",
        fontSize: 17,
        fontStyle: "normal",
        letterSpacing: 0,
        textAlign: "left",
        fontWeight: "bold",
        color: AppColors.BLACK*/
  },
  button_text_form: {
    //width: 60,
    paddingRight: 10,
    height: 19,
    fontFamily: "Roboto",
    fontSize: 18,
    fontWeight: "bold",
    fontStyle: "normal",
    letterSpacing: 0,
    textAlign: "left",
    color: "black",
    textTransform: "capitalize",
  },
  text_form: {
    marginLeft: 22.5,
    color: AppColors.WHITE,
    fontFamily: "Roboto-Regular",
    fontSize: 15,
    marginVertical: 0,
  },
  text_form_guest: {
    marginLeft: 12.5,
    color: AppColors.WHITE,
    fontFamily: "Roboto-Bold",
    fontSize: 15,
    marginVertical: 0,
  },
  text_form_logo_color: {
    color: AppColors.LOGO_COLOR,
    fontFamily: "Roboto-Bold",
    fontSize: 15,
  },
  text_form_white_color: {
    color: AppColors.WHITE,
    fontFamily: "Roboto-Bold",
    fontSize: 15,
  },
  check_form: {
    textAlign: "left",
    paddingLeft: 5,
    // width: 60,
    height: 19,
    fontFamily: "Roboto",
    fontSize: 16,
    fontWeight: "500",
    fontStyle: "normal",
    letterSpacing: 0,
    color: AppColors.LOGO_COLOR,
  },
  text_home_featured: {
    fontFamily: "Roboto-Bold",
    fontSize: 16,
    color: "#E1D3BE",
  },
  /*My Favorites*/
  text_list_tittle_left: {
    // width: 42,
    height: 25,
    fontFamily: "Roboto",
    fontSize: 13,
    fontWeight: "normal",
    fontStyle: "normal",
    letterSpacing: 0,
    textAlign: "left",
    color: AppColors.LOGO_COLOR,
  },
  text_list_tittle_right: {
    height: 25,
    fontFamily: "Roboto",
    fontSize: 13,
    fontWeight: "300",
    fontStyle: "normal",
    letterSpacing: 0,
    textAlign: "left",
    color: AppColors.LOGO_COLOR,
  },
  name_of_the_place: {
    //width: 88,
    height: 29,
    fontFamily: "Roboto",
    fontSize: 16,
    fontWeight: "bold",
    fontStyle: "normal",
    letterSpacing: 0,
    textAlign: "left",
    color: AppColors.WHITE,
  },
  iconLists: {
    paddingTop: 20,
    textAlign: "right",
    width: 500,
    height: 32,
    paddingLeft: 100,
  },
  start_number: {
    width: 24,
    height: 20,
    fontFamily: "Roboto",
    fontSize: 13,
    fontWeight: "normal",
    fontStyle: "normal",
    letterSpacing: 0,
    textAlign: "right",
    color: AppColors.WHITE,
  },
  start_percent: {
    // width: 24,
    height: 15,
    fontFamily: "Roboto",
    fontSize: 13,
    fontWeight: "normal",
    fontStyle: "normal",
    letterSpacing: 0,
    textAlign: "left",
    color: AppColors.WHITE,
  },
  text_home_link: {
    alignSelf: "flex-end",
    fontSize: 12,
    color: AppColors.LOGO_COLOR,
    textDecorationLine: "underline",
  },
  list_rectangle: {
    // width: 155,
    height: 180,
    // borderRadius: 12,
    // backgroundColor: "#22222c"
    flex: 1,
    //resizeMode: "contain"
  },
  paragraph: {
    textAlign: "center",
    padding: 2,
    fontFamily: "Roboto",
    fontSize: 17,
    fontWeight: "500",
    fontStyle: "normal",
    letterSpacing: 0,
  },
  img_favorite: {},
  text_center: {
    textAlign: "center",
  },
  text_right: {
    textAlign: "right",
  },
  text_left: {
    textAlign: "left",
  },
  content: {
    padding: 4,
  },
  card: {
    margin: 4,
  },
  half: {
    flex: 1,
  },
  content_center: {
    alignContent: "center",
  },
  text_top14: {
    paddingHorizontal: 4,
    paddingTop: 14,
  },
  numeric_input: {
    fontSize: 13,
  },
  image_container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  input: {
    marginRight: 10,
    marginLeft: 10,
    backgroundColor: AppColors.INPUT_BG,
    color: "white",
  },
  input_flat: {
    marginRight: 10,
    marginLeft: 10,
    backgroundColor: AppColors.BG,
  },
  input_flat_guest: {
    backgroundColor: AppColors.BG,
  },
  input_special: {
    backgroundColor: AppColors.BG,
    width: "100%",
  },
  input_4: {
    marginRight: 10,
    marginLeft: 10,
    borderColor: AppColors.TRANSPARENCY,
  },
  input_0: {},
  secondary: {
    backgroundColor: AppColors.SECONDARY,
  },
  first_row: {
    flex: 2,
  },
  button_simple: {
    color: AppColors.WHITE,
    marginHorizontal: 10,
    marginVertical: 4,
    textTransform: "capitalize",
  },
  venue_pic: {
    width: 96,
    height: 96,
    marginTop: 5,
    borderRadius: 5,
    marginEnd: 15,
  },
  venue_title: {
    fontFamily: "Roboto-Bold",
    fontSize: 20,
    color: AppColors.WHITE,
    paddingTop: 10,
  },
  venue_detail: {
    fontSize: 12,
    color: AppColors.WHITE,
  },
  venue_detail_icon: {
    backgroundColor: AppColors.BARS,
  },
  pointer: {
    width: 5,
    marginLeft: -100,
    marginTop: -65,
  },
  flat_list: {
    backgroundColor: AppColors.BG,
    flex: 1,
  },
  list_item_white: {
    color: AppColors.WHITE,
  },
  icon_white: {
    color: AppColors.WHITE,
  },
  mastercard1234: {
    // width: 123,
    height: 19,
    fontFamily: "Roboto",
    fontSize: 16,
    fontWeight: "bold",
    fontStyle: "normal",
    letterSpacing: 0,
    textAlign: "left",
    color: AppColors.WHITE,
  },
  jakeJohnson: {
    width: 96,
    height: 22,
    fontFamily: "Roboto",
    fontSize: 16,
    fontWeight: "normal",
    fontStyle: "normal",
    lineHeight: 22,
    letterSpacing: -0.41,
    textAlign: "center",
    color: AppColors.WHITE,
  },
  date_card: {
    width: 41,
    height: 22,
    fontFamily: "Roboto",
    fontSize: 16,
    fontWeight: "normal",
    fontStyle: "normal",
    lineHeight: 22,
    letterSpacing: -0.41,
    textAlign: "center",
    color: AppColors.WHITE,
  },
  login: {
    width: 75,
    height: 22,
    fontFamily: "Roboto",
    fontSize: 16,
    fontWeight: "bold",
    fontStyle: "normal",
    lineHeight: 22,
    letterSpacing: -0.41,
    textAlign: "center",
    color: AppColors.WHITE,
  },
  cardNumber: {
    // width: 72,
    // height: 22,
    fontFamily: "Roboto",
    fontSize: 13,
    fontWeight: "bold",
    fontStyle: "normal",
    lineHeight: 22,
    letterSpacing: -0.41,
    textAlign: "left",
    color: AppColors.WHITE,
    marginBottom: 10,
    marginLeft: 15,
  },
  line: {
    borderBottomColor: AppColors.GREY,
    borderBottomWidth: 1,
    marginTop: 25,
    marginBottom: 25,
  },
  labelTitle: {
    width: 749,
    height: 22,
    fontFamily: "Roboto",
    fontSize: 16,
    fontWeight: "normal",
    fontStyle: "normal",
    lineHeight: 22,
    letterSpacing: -0.41,
    textAlign: "left",
    color: "#d1d3d3",
    marginLeft: 15,
    marginRight: 160,
  },
  expiration: {
    // width: 56,
    height: 22,
    fontFamily: "Roboto",
    fontSize: 13,
    fontWeight: "bold",
    fontStyle: "normal",
    lineHeight: 22,
    letterSpacing: -0.41,
    textAlign: "left",
    paddingLeft: 10,
    paddingRight: 70,
    color: AppColors.WHITE,
  },
  label_title: {
    height: 22,
    fontFamily: "Roboto",
    fontSize: 16,
    fontWeight: "normal",
    fontStyle: "normal",
    lineHeight: 22,
    letterSpacing: -0.41,
    textAlign: "left",
    paddingLeft: 10,
    paddingRight: 70,
    color: "#d1d3d3",
  },
  image_list: {
    flex: 1,
    // resizeMode: "center",
    width: 163,
    height: 163,
    marginRight: 10,
  },
  chat_inbox_text: {
    position: "absolute",
    bottom: 0,
    marginBottom: 15,
    width: "100%",
  },
  profile_name: {
    fontFamily: "Roboto-Bold",
    fontSize: 20,
    color: AppColors.WHITE,
  },
  profile_email: {
    fontFamily: "Roboto",
    fontSize: 13,
    color: "#ffffff66",
    textDecorationLine: "underline",
  },
  start5: {},
  start5_white: {},
  switch: {},
  switch_large: {},
  text_notifications: {
    color: AppColors.WHITE,
    fontSize: 16,
    paddingTop: 5,
  },
  logo_image_style: {
    width: moderateScale(121),
    height: moderateScale(22),
    resizeMode: "contain",
    marginLeft: scale(30),
  },
  header_style: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: scale(13),
    marginBottom: verticalScale(20),
    marginTop: verticalScale(10),
  },
});